CREATE DATABASE [IF NOT EXISTS] instadron;


CREATE TABLE IF NOT EXISTS user (
	id INT AUTO_INCREMENT,
	user_id VARCHAR(255) NOT NULL,
	biography TEXT,
	public_profile BOOLEAN,
	fb_page VARCHAR(255),
	full_name VARCHAR(255),
	is_business_account BOOLEAN,
	is_private BOOLEAN,
	username VARCHAR(255) NOT NULL,
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	ADD UNIQUE(user_id);
	PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS followers_count (
	id INT AUTO_INCREMENT,
	user_id VARCHAR(255) NOT NULL,
	followers_count INTEGER,
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	FOREIGN KEY (user_id) REFERENCES user(user_id) ON DELETE CASCADE
)

CREATE TABLE IF NOT EXISTS followers (
	id INT AUTO_INCREMENT,
	user_id VARCHAR(255) NOT NULL,
	follower_id VARCHAR(255),
	username VARCHAR(255),
	full_name VARCHAR(255),
	profile_pic TEXT,
	is_private BOOLEAN,
	is_following BOOLEAN,
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	FOREIGN KEY (user_id) REFERENCES user(user_id) ON DELETE CASCADE
);
